name: mobsuite_recon
description: A tool to reconstruct plasmids in bacterial assemblies
keywords:
  - bacteria
  - plasmid
  - cluster
tools:
  - mobsuite:
      description: Software tools for clustering, reconstruction and typing of plasmids
        from draft assemblies.
      homepage: https://github.com/phac-nml/mob-suite
      documentation: https://github.com/phac-nml/mob-suite
      tool_dev_url: https://github.com/phac-nml/mob-suite
      doi: "10.1099/mgen.0.000435"
      licence: ["Apache License, Version 2.0"]
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: A bacterial genome assembly in FASTA format
        pattern: "*.{fasta,fa,fna}"
output:
  - chromosome:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*/chromosome.fasta":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*/chromosome.fasta"
  - contig_report:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*/contig_report.txt":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*/contig_report.txt"
  - plasmids:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*/plasmid_*.fasta":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*/plasmid_*.fasta"
  - mobtyper_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*/mobtyper_results.txt":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "mobtyper_results.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@rpetit3"
maintainers:
  - "@rpetit3"
